"""Default mutable file responsibilities per scaffold type."""

from __future__ import annotations

SCAFFOLD_FILE_RESPONSIBILITIES: dict[str, list[tuple[str, str, list[str]]]] = {
    "vision_classification": [
        ("src/data.py",          "Dataset loading and train/val/test split only",
         ["load_image_dataset"]),
        ("src/models.py",        "Model architecture construction only",
         ["build_image_model"]),
        ("src/train.py",         "Training loop only (forward pass, optimizer, LR schedule)",
         ["train_image_model"]),
        ("src/evaluate.py",      "Evaluation / metric computation only",
         ["evaluate_image_model"]),
        ("src/experiment_impl.py", "Experiment orchestration: calls data/model/train/evaluate in order",
         ["run_single_experiment", "run_selected_experiments"]),
        ("src/experiment_registry.py", "Experiment selection and definition only",
         ["select_experiments", "build_experiment_definitions"]),
        ("src/result_reducer.py", "Result payload assembly only",
         ["build_result_payload"]),
        ("src/validation.py",    "Quality gate / metric threshold checks only",
         ["derive_validation_outcome"]),
    ],
    "tabular_supervised": [
        ("src/preprocess.py",    "Raw data loading and cleaning only",
         ["load_tabular_dataset"]),
        ("src/features.py",      "Feature engineering only",
         ["build_features"]),
        ("src/models.py",        "Model construction only",
         ["build_tabular_model"]),
        ("src/train.py",         "Training loop only",
         ["train_tabular_model"]),
        ("src/evaluate.py",      "Evaluation / metric computation only",
         ["evaluate_tabular_model"]),
        ("src/experiment_impl.py", "Experiment orchestration only",
         ["run_single_experiment", "run_selected_experiments"]),
        ("src/experiment_registry.py", "Experiment selection only",
         ["select_experiments", "build_experiment_definitions"]),
        ("src/result_reducer.py", "Result payload assembly only",
         ["build_result_payload"]),
        ("src/validation.py",    "Quality gate checks only",
         ["derive_validation_outcome"]),
    ],
    "timeseries_forecasting": [
        ("src/dataset.py",       "Time-series data loading and windowing only",
         ["load_timeseries_dataset"]),
        ("src/features.py",      "Feature engineering only",
         ["build_features"]),
        ("src/models.py",        "Model construction only",
         ["build_forecast_model"]),
        ("src/forecast.py",      "Forecast generation only",
         ["run_forecast"]),
        ("src/backtest.py",      "Backtest evaluation only",
         ["run_backtest"]),
        ("src/experiment_impl.py", "Experiment orchestration only",
         ["run_single_experiment", "run_selected_experiments"]),
        ("src/experiment_registry.py", "Experiment selection only",
         ["select_experiments", "build_experiment_definitions"]),
        ("src/result_reducer.py", "Result payload assembly only",
         ["build_result_payload"]),
        ("src/validation.py",    "Quality gate checks only",
         ["derive_validation_outcome"]),
    ],
    "_default": [
        ("src/experiment_impl.py", "Experiment orchestration only",
         ["run_single_experiment", "run_selected_experiments"]),
        ("src/experiment_registry.py", "Experiment selection only",
         ["select_experiments", "build_experiment_definitions"]),
        ("src/result_reducer.py", "Result payload assembly only",
         ["build_result_payload"]),
        ("src/validation.py",    "Quality gate checks only",
         ["derive_validation_outcome"]),
    ],
}
